# Generated by Django 4.1.4 on 2023-01-04 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentMethod', models.CharField(max_length=100)),
                ('taxPrice', models.FloatField()),
                ('shippingPrice', models.FloatField()),
                ('totalPrice', models.FloatField()),
                ('isPaid', models.BooleanField()),
                ('paidAt', models.BooleanField()),
                ('isDelivered', models.BooleanField()),
                ('deliveredAt', models.DateField()),
                ('createAt', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('brand', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=1000)),
                ('rating', models.FloatField()),
                ('numReviews', models.IntegerField()),
                ('price', models.FloatField()),
                ('countInStock', models.IntegerField()),
                ('createAt', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('first_Name', models.CharField(max_length=100)),
                ('last_Name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('is_superuser', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('postalCode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('shippingPrice', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.order')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('comment', models.CharField(max_length=1000)),
                ('createAt', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.user'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.user'),
        ),
    ]
