# Generated by Django 4.1.4 on 2023-04-20 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_shippingaddress_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_Name',
            new_name='last_name',
        ),
    ]
