# Generated by Django 4.1.4 on 2023-04-20 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_first_name_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='createAt',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveredAt',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='order',
            name='isDelivered',
            field=models.BooleanField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='order',
            name='paidAt',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
